use axum::{Router, routing::{get, post, put}};
use tower_http::cors::CorsLayer;
use tower_http::trace::{DefaultMakeSpan, DefaultOnResponse, TraceLayer};
use tracing::Level;

use crate::handlers::{amf_configuration, configuration, health, nsag_configuration, nsi_configuration, nssaiavailability, nsselection, nssrg_configuration, policy_configuration, snssai_mapping_configuration, subscription_configuration};
use crate::types::AppState;

pub fn create_routes(state: AppState) -> Router {
    Router::new()
        .route("/health", get(health::health_check))
        .route("/status", get(health::status))
        .route(
            "/nssf-config/v1/slices",
            get(configuration::list_slices).post(configuration::create_slice),
        )
        .route(
            "/nssf-config/v1/slices/{id}",
            put(configuration::update_slice).delete(configuration::delete_slice),
        )
        .route(
            "/nssf-config/v1/nsi",
            get(nsi_configuration::list_nsi).post(nsi_configuration::create_nsi),
        )
        .route(
            "/nssf-config/v1/nsi/{nsi_id}",
            get(nsi_configuration::get_nsi)
                .put(nsi_configuration::update_nsi)
                .delete(nsi_configuration::delete_nsi),
        )
        .route(
            "/nssf-config/v1/amf-sets",
            get(amf_configuration::list_amf_sets).post(amf_configuration::create_amf_set),
        )
        .route(
            "/nssf-config/v1/amf-sets/{amf_set_id}",
            get(amf_configuration::get_amf_set)
                .put(amf_configuration::update_amf_set)
                .delete(amf_configuration::delete_amf_set),
        )
        .route(
            "/nssf-config/v1/amf-service-sets",
            get(amf_configuration::list_amf_service_sets)
                .post(amf_configuration::create_amf_service_set),
        )
        .route(
            "/nssf-config/v1/amf-service-sets/{amf_service_set_id}",
            get(amf_configuration::get_amf_service_set)
                .put(amf_configuration::update_amf_service_set)
                .delete(amf_configuration::delete_amf_service_set),
        )
        .route(
            "/nssf-config/v1/amf-instances",
            get(amf_configuration::list_amf_instances)
                .post(amf_configuration::create_amf_instance),
        )
        .route(
            "/nssf-config/v1/amf-instances/{nf_instance_id}",
            get(amf_configuration::get_amf_instance)
                .put(amf_configuration::update_amf_instance)
                .delete(amf_configuration::delete_amf_instance),
        )
        .route(
            "/nssf-config/v1/policies",
            get(policy_configuration::list_policies)
                .post(policy_configuration::create_policy),
        )
        .route(
            "/nssf-config/v1/policies/{policy_id}",
            get(policy_configuration::get_policy)
                .put(policy_configuration::update_policy)
                .delete(policy_configuration::delete_policy),
        )
        .route(
            "/nssf-config/v1/subscriptions",
            get(subscription_configuration::list_subscriptions)
                .post(subscription_configuration::create_subscription),
        )
        .route(
            "/nssf-config/v1/subscriptions/{supi}",
            get(subscription_configuration::get_subscription)
                .put(subscription_configuration::update_subscription)
                .delete(subscription_configuration::delete_subscription),
        )
        .route(
            "/nssf-config/v1/nsags",
            get(nsag_configuration::list_nsags).post(nsag_configuration::create_nsag),
        )
        .route(
            "/nssf-config/v1/nsags/{nsag_id}",
            get(nsag_configuration::get_nsag)
                .put(nsag_configuration::update_nsag)
                .delete(nsag_configuration::delete_nsag),
        )
        .route(
            "/nssf-config/v1/nssrgs",
            get(nssrg_configuration::list_nssrgs).post(nssrg_configuration::create_nssrg),
        )
        .route(
            "/nssf-config/v1/nssrgs/{nssrg_id}",
            get(nssrg_configuration::get_nssrg)
                .put(nssrg_configuration::update_nssrg)
                .delete(nssrg_configuration::delete_nssrg),
        )
        .route(
            "/nssf-config/v1/snssai-mappings",
            get(snssai_mapping_configuration::list_snssai_mappings)
                .post(snssai_mapping_configuration::create_snssai_mapping),
        )
        .route(
            "/nnssf-nsselection/v2/network-slice-information",
            get(nsselection::get_network_slice_information),
        )
        .route(
            "/nssf-config/v1/snssai-mappings/{mapping_id}",
            get(snssai_mapping_configuration::get_snssai_mapping)
                .put(snssai_mapping_configuration::update_snssai_mapping)
                .delete(snssai_mapping_configuration::delete_snssai_mapping),
        )
        .route(
            "/nnssf-nssaiavailability/v1/subscriptions",
            post(nssaiavailability::create_subscription),
        )
        .route(
            "/nnssf-nssaiavailability/v1/subscriptions/{subscription_id}",
            get(nssaiavailability::get_subscription)
                .patch(nssaiavailability::update_subscription)
                .delete(nssaiavailability::delete_subscription),
        )
        .with_state(state)
        .layer(
            TraceLayer::new_for_http()
                .make_span_with(DefaultMakeSpan::new().level(Level::INFO))
                .on_response(DefaultOnResponse::new().level(Level::INFO)),
        )
        .layer(CorsLayer::permissive())
}
